site_name: Dokusei Documentation
site_description: Documentation for the Dokusei bot.
site_url: https://dunc4nnt.github.io/Dokusei-Docs/
site_author: Dunc4nNT

dev_addr: 127.0.0.1:8000

copyright: Copyright &copy; 2022 Dunc4nNT

repo_url: https://github.com/Dunc4nNT/Dokusei-Docs/
repo_name: Dunc4nNT/Dokusei-Docs
edit_uri: edit/master/docs/

theme:
  name: material
  language: en
  logo: assets/icons/dokusei_notext.png
  favicon: assets/icons/favicon.ico
  icon:
    repo: material/git
    edit: material/file-document-edit-outline
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: deep purple
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: grey
      accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.share
    - search.highlight

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.betterem:
      smart_enable: all
  - attr_list
  - tables

extra:
  social:
    - icon: material/home
      link: https://dunc4nnt.github.io/Dokusei-Website
    - icon: material/view-dashboard
      link: https://dunc4nnt.github.io/Dokusei-Dashboard
    - icon: fontawesome/brands/github
      link: https://github.com/Dunc4nNT
    - icon: fontawesome/solid/globe
      link: https://dunc4nnt.github.io/

extra_css:
  - assets/css/styles.css

nav:
  - Home:
    - Dokusei: index.md
    - Table of Contents: table_of_contents.md
    - Guide: guide.md
    - FAQ: faq.md
    - Changelog: changelog.md
  - Config:
    - Bot Manager: config/bot_manager.md
    - Prefixes: config/prefixes.md
  - Economy & Levels:
    - Economy: economy_and_levels/economy.md
    - Crypto: economy_and_levels/crypto.md
    - Levels: economy_and_levels/levels.md
    - User Cards: economy_and_levels/user_cards.md
  - Fun:
    - Fun: fun/fun.md
    - Game Information: fun/game_stats.md
    - Games: fun/games.md
    - Image Manipulation: fun/image_manipulations.md
    - Text Manipulation: fun/text_manipulations.md
  - Informatic:
    - Informatic: informatic/informatic.md
    - Statistics: informatic/statistics.md
  - Logging:
    - Logging: logging/logging.md
    - Welcomer: logging/welcomer.md
  - Moderation:
    - Automod: moderation/automod.md
    - Moderation: moderation/moderation.md
    - Modmail: moderation/modmail.md
    - Reports: moderation/reports.md
    - Verification: moderation/verification.md
  - Music:
    - Music: music/music.md
    - Playlists: music/playlists.md
  - Roles:
    - Automatic Roles: roles/auto_roles.md
    - Reaction Roles: roles/reaction_roles.md
    - Roles: roles/roles.md
    - Self Roles: roles/self_roles.md
    - Voice Roles: roles/voice_roles.md
  - Tags:
    - Tags: tags/tags.md
    - Advanced Use: tags/advanced_use.md
    - Examples: tags/examples.md
  - Utilities:
    - To Do: utilities/todo.md
    - Utilities: utilities/utility.md
    - Reminders & Notifications:
      - Reminders: utilities/reminders_and_notifications/reminders.md
      - Tagwords: utilities/reminders_and_notifications/tagwords.md
      - Timed Messages: utilities/reminders_and_notifications/timed_messages.md
      - Triggers: utilities/reminders_and_notifications/triggers.md
      - Twitch: utilities/reminders_and_notifications/twitch.md
    - User Feedback:
      - Polls: utilities/user_feedback/polls.md
      - Starboard: utilities/user_feedback/starboard.md
      - Suggestions: utilities/user_feedback/suggestions.md
  - Voice:
    - Voice Manager: voice/voice_manager.md
  - Developer:
    - Developer: developer/developer.md
